### PR TITLE
Adds param to turn off rejection by annotation for epoch creation.

### PR DESCRIPTION
**Pull request by nordme**
Hi Eric, 

I need to be able to turn off rejection by annotation during epoch creation for our Prek preprocessing. I've drafted this PR for you. Would you take a look and see if it's done properly? I need your head position fixes for Prek, so I worked off of your headpos branch. I know you're super busy at the hackathon... sorry for the timing. 

Thanks, 

Erica

### CODE REVIEW

**Comment by larsoner** [comment]
So there are segments in this data with annotations that have description `BAD_`, but these are supposed to be kept during epoching? The code seems fine, but the pipeline seems a bit odd. It might be better to rename the annotation descriptions in these datasets if the segments are actually not meant to be treated as bad.

But if that's not tractable, then we can probably live with this option

**Comment by nordme** [comment]
Yeah. We've got a bunch of 5 year olds periodically scratching their EOGs
and throwing off SSP. We need to toss the bad segments for the purpose of
creating appropriate blinks projectors for them during SSP, but their brain
responses to the images they're watching should be perfectly intact, so we
want to keep the trials.

My reasoning is that this parameter will be True by default and doesn't
even need to show up on most mnefun scripts. It can just be there for the
weird case here and there, like Prek, where we have a bunch of subjects
interfering with their external electrodes.

But if you have a better idea for handling this issue, let me know. :)


Erica Peterson
Research Scientist
Institute for Learning and Brain Sciences
University of Washington
Box 357988
Seattle, WA 98195
(206) 685-2842

**Comment by larsoner** [comment]
I would annotate the EOG stuff with `EOG_*` something, then in the EOG stuff set `skip_by_annotation='eog'`. Then annotate bad segments with `BAD_*` as usual, since `reject_by_annotation='bad'` is the default in more and more in MNE it's more likely to do the right thing.

But we can still add this param for now, and you can change the workflow later if you want (and add a `reject_eog_epochs_by_annot` param later).

**Comment by larsoner** [comment]
Cherry-picked your commit, it's in `LABSN/mnefun:master` now

**Comment by nordme** [comment]
Thanks, Eric!!

Erica Peterson
Research Scientist
Institute for Learning and Brain Sciences
University of Washington
Box 357988
Seattle, WA 98195
(206) 685-2842

**Pull request closed without merging**
